### ISSUE TITLE
closet backend

### ISSUE THREAD

**Issue by baaaam771** [ProjectFFF/FFF#17]
closet CRUD backend 논의
해결 과제
new->record
- [x] Create

- [x] Read

- [ ] Update

- [x] Delete
---------------------------
record->closet
- [ ] Create

- [ ] Read

- [ ] Update

- [ ] Delete
------------------------------

- [ ] 카테고리 검색기능

- [x] 사진 업로드

- [x] 계산기 기능
--------------------------

- [x] pk 값 할당

- [ ] 선택한 값  그대로 호출

- [ ] 옷장에 최종 등록

**Comment by baaaam771** [comment]
해결 과제

- [ ] Create

- [ ] Read

- [ ] Update

- [ ] Delete

**Comment by baaaam771** [comment]
https://github.com/ProjectFFF/FFF/issues/10#issuecomment-691881951
카테고리 참고용

**Comment by baaaam771** [comment]
백엔드 개발 중 새로입력란에 해당하는 model 수립
새로입력 페이지 기본적인 레이아웃 제작

**Comment by baaaam771** [comment]
내 옷장 등록하기를 하면 어디로 등록이 되는 거지?
![내 옷장](https://user-images.githubusercontent.com/60038592/94051849-1fd35a00-fe13-11ea-90d5-970cd7d431fe.PNG)

**Comment by baaaam771** [comment]
sizecompare model duplicate
`from .models import Compare`
`from closets.models import Newcloth`

**Comment by baaaam771** [comment]
admin으로 데이터 값 입력하면 보임
아직 이미지는 처리 못함
![기입](https://user-images.githubusercontent.com/60038592/94999855-4d7c8800-05f7-11eb-9b32-624984858744.PNG)

**Comment by baaaam771** [comment]
새로입력에서 데이터 입력하고 사이즈 기록으로 넘어갈때 오류발생

> NOT NULL constraint failed: closets_newcloth.total_length

이유는 아직 모르겠는데 구글링도 해보고 이미지 데이터도 기입해보면 뭔가 알게 될 것 같음
![에러](https://user-images.githubusercontent.com/60038592/94999889-8583cb00-05f7-11eb-9059-4f1622b13508.PNG)

> Environment:


Request Method: GET
Request URL: http://127.0.0.1:8000/closets/create/?cloth_name=%ED%85%8C%EC%8A%A4%ED%8A%B8&shoulder=1&chest=2&arm=3&total_length=4

Django Version: 3.1.1
Python Version: 3.8.3
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'main',
 'accounts',
 'closets',
 'mysettings',
 'sizecompares',
 'othersclosets',
 'measureguides']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "C:\Users\LeeBeomGi\Desktop\fff\myvenv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\LeeBeomGi\Desktop\fff\myvenv\lib\site-packages\django\db\backends\sqlite3\base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)

The above exception (NOT NULL constraint failed: closets_newcloth.total_length) was the direct cause of the following exception:
  File "C:\Users\LeeBeomGi\Desktop\fff\myvenv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\LeeBeomGi\Desktop\fff\myvenv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\LeeBeomGi\Desktop\fff\FFF\closets\views.py", line 24, in create
    cloth.save() #데이터베이스에 저장해라
  File "C:\Users\LeeBeomGi\Desktop\fff\myvenv\lib\site-packages\django\db\models\base.py", line 753, in save
    self.save_base(using=using, force_insert=force_insert,
  File "C:\Users\LeeBeomGi\Desktop\fff\myvenv\lib\site-packages\django\db\models\base.py", line 790, in save_base
    updated = self._save_table(
  File "C:\Users\LeeBeomGi\Desktop\fff\myvenv\lib\site-packages\django\db\models\base.py", line 895, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "C:\Users\LeeBeomGi\Desktop\fff\myvenv\lib\site-packages\django\db\models\base.py", line 933, in _do_insert
    return manager._insert(
  File "C:\Users\LeeBeomGi\Desktop\fff\myvenv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\LeeBeomGi\Desktop\fff\myvenv\lib\site-packages\django\db\models\query.py", line 1249, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Users\LeeBeomGi\Desktop\fff\myvenv\lib\site-packages\django\db\models\sql\compiler.py", line 1397, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\LeeBeomGi\Desktop\fff\myvenv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "C:\Users\LeeBeomGi\Desktop\fff\myvenv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\LeeBeomGi\Desktop\fff\myvenv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\LeeBeomGi\Desktop\fff\myvenv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\LeeBeomGi\Desktop\fff\myvenv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\LeeBeomGi\Desktop\fff\myvenv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\LeeBeomGi\Desktop\fff\myvenv\lib\site-packages\django\db\backends\sqlite3\base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)

Exception Type: IntegrityError at /closets/create/
Exception Value: NOT NULL constraint failed: closets_newcloth.total_length
