### ISSUE TITLE
새로입력->사이즈 기록 error

### ISSUE THREAD

**Issue by baaaam771** [ProjectFFF/FFF#19]
새로입력에서 데이터 입력하고 사이즈 기록으로 넘어갈때 오류발생

> NOT NULL constraint failed: closets_newcloth.total_length

이유는 아직 모르겠는데 구글링도 해보고 이미지 데이터도 기입해보면 뭔가 알게 될 것 같음
![에러](https://user-images.githubusercontent.com/60038592/94999889-8583cb00-05f7-11eb-9059-4f1622b13508.PNG)

> Environment:

Request Method: GET
Request URL: http://127.0.0.1:8000/closets/create/?cloth_name=%ED%85%8C%EC%8A%A4%ED%8A%B8&shoulder=1&chest=2&arm=3&total_length=4

Django Version: 3.1.1
Python Version: 3.8.3
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'main',
 'accounts',
 'closets',
 'mysettings',
 'sizecompares',
 'othersclosets',
 'measureguides']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Traceback (most recent call last):
  File "C:\Users\LeeBeomGi\Desktop\fff\myvenv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\LeeBeomGi\Desktop\fff\myvenv\lib\site-packages\django\db\backends\sqlite3\base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)

The above exception (NOT NULL constraint failed: closets_newcloth.total_length) was the direct cause of the following exception:
  File "C:\Users\LeeBeomGi\Desktop\fff\myvenv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\LeeBeomGi\Desktop\fff\myvenv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\LeeBeomGi\Desktop\fff\FFF\closets\views.py", line 24, in create
    cloth.save() #데이터베이스에 저장해라
  File "C:\Users\LeeBeomGi\Desktop\fff\myvenv\lib\site-packages\django\db\models\base.py", line 753, in save
    self.save_base(using=using, force_insert=force_insert,
  File "C:\Users\LeeBeomGi\Desktop\fff\myvenv\lib\site-packages\django\db\models\base.py", line 790, in save_base
    updated = self._save_table(
  File "C:\Users\LeeBeomGi\Desktop\fff\myvenv\lib\site-packages\django\db\models\base.py", line 895, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "C:\Users\LeeBeomGi\Desktop\fff\myvenv\lib\site-packages\django\db\models\base.py", line 933, in _do_insert
    return manager._insert(
  File "C:\Users\LeeBeomGi\Desktop\fff\myvenv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\LeeBeomGi\Desktop\fff\myvenv\lib\site-packages\django\db\models\query.py", line 1249, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Users\LeeBeomGi\Desktop\fff\myvenv\lib\site-packages\django\db\models\sql\compiler.py", line 1397, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\LeeBeomGi\Desktop\fff\myvenv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "C:\Users\LeeBeomGi\Desktop\fff\myvenv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\LeeBeomGi\Desktop\fff\myvenv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\LeeBeomGi\Desktop\fff\myvenv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\LeeBeomGi\Desktop\fff\myvenv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\LeeBeomGi\Desktop\fff\myvenv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\LeeBeomGi\Desktop\fff\myvenv\lib\site-packages\django\db\backends\sqlite3\base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)

Exception Type: IntegrityError at /closets/create/
Exception Value: NOT NULL constraint failed: closets_newcloth.total_length

_Originally posted by @baaaam771 in https://github.com/ProjectFFF/FFF/issues/17#issuecomment-703151655_

**Comment by baaaam771** [comment]
일단 이미지 데이터 문제는 아닌듯
모델에서 정의한 값들을 사용을 안할때 한번씩 error가 생기던데 그 문제는 아닌 것 같다
![이미지](https://user-images.githubusercontent.com/60038592/95000765-8ff59300-05fe-11eb-9a74-52209962089a.PNG)

**Comment by baaaam771** [comment]
새로입력에서 사이즈 기록으로 게시 오류 문제 해결
근데 이미지 파일이 인식이 안된다
현재 admin으로 입력한 이미지만 인식가능
아마 경로 문제 일것 같은데 또 찾아봐야겠다.
![이미지 에러](https://user-images.githubusercontent.com/60038592/95001277-61c68200-0603-11eb-839d-9696fd425017.PNG)

**Comment by baaaam771** [comment]
해결 방법은 함수 수정함

def create(request): #입력 내용 데이터베이스에 넣어줌
    cloth= Newcloth()
    cloth.cloth_name= request.GET['cloth_name']
    cloth.shoulder= request.GET['shoulder']
    cloth.chest= request.GET['chest']
    cloth.arm= request.GET['arm']
    cloth.total_length= request.GET['total_length']
    cloth.image= request.GET['image']
    cloth.save()
    return render(request, 'record.html')
